### ISSUE TITLE
Cargo dosen't update properly

### ISSUE THREAD

**Issue by xanderio** [founderio/edrouteplanner#4]
If you change the max cargo on the right.
the amount you pick on a station is not update properly

**Comment by founderio** [comment]
That behaviour is actually by design.
The amount is saved per transaction. The maximum cargo is only fetched at transaction creation, after that it will not change.

Solution proposal: I will save:
- Manually set cargo amount -> will not change
- Automatically set cargo (maximum amount) will be saved as 0 internally. On calculation & display it will fetch the maximum cargo from the pilot settings - essentially do the same as before, just one step later. This waay I can also display MAX (xyz) as amount to make it clearer.
